name: 'auto_snow_mask_pii'
version: '1.0.0'
config-version: 2
profile: 'pii'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"

models:
  auto_snow_mask_pii:
    materialized: view
    int:
      materialized: table
      +tags: "main"
      tables:
      - name: customer_info_int
        columns:
          - name: country
            meta:
              pii: IGNORE
          
      post-hook: 
        - "{{ auto_snow_mask.apply_masking_policy(var('run_mode')) }}"
    stg:
      materialized: table
      +tags: "main"
    mart:
      +tags: "main"
      base: