name: 'auto_snow_mask_pii'
version: '1.0.0'
config-version: 2
profile: 'pii'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"

models:
  auto_snow_mask_pii:
    materialized: view
    # generic / default function test
    int:
      materialized: table
      +tags: "main"
      tables:
      - name: customer_info_int
        columns:
          # ignore PII action
          - name: country
            meta:
              pii: IGNORE
          # explicit masking requirement
          - name: BITCOIN_ADDRESS
            meta:
              pii: TEXT
          - name: ETHEREUM_ADDRESS
            meta:
              pii: TEXT
          - name: PASSWORD
            meta:
              pii: TEXT
    # post-hook action to trigger Auto masking PII package.
      post-hook: 
        - "{{ auto_snow_mask.apply_masking_policy(var('run_mode'), threshold=0.2) }}"
    stg:
      materialized: table
      +tags: "main"
    mart:
      +tags: "main"
      base: