version: 2

models:
  - name: customer_info
    columns:
      - name: City
      - name: Country
        meta:
          pii: IGNORE
      - name: Gender
        meta:
          pii: IGNORE
      - name: Last_name
    meta:
      pii: TEXT
      pii_custom: custom_masking_policy